<?php
declare(strict_types=1);

namespace AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function getAllPosts()
    {
        $qb = $this->createQueryBuilder('p')
            ->select('p', 'u')
            ->leftJoin('p.user', 'u')
            ->getQuery();
       
        return $qb;
    }

    public function getUserPosts(int $userId)
    {
        $qb = $this->createQueryBuilder('p')
            ->select('p', 'u')
            ->join('p.user', 'u')
            ->where('p.user = :user')
            ->setParameter('user', $userId)
            ->getQuery();
       
        return $qb;
    }

    public function getPost($id)
    {
        $qb = $this->createQueryBuilder('p')
            ->select('p', 'u')
            ->leftJoin('p.user', 'u')
            ->where('p.id = :id')
            ->setParameter('id', $id)
            ->getQuery();
        $result = $qb->getOneOrNullResult();

        return $result;
    }

    public function getUserPost($id, $userId)
    {
        $qb = $this->createQueryBuilder('p')
            ->select('p', 'u')
            ->leftJoin('p.user', 'u')
            ->where('p.id = :id')
            ->andWhere('u.id = :userId')
            ->setParameter('id', $id)
            ->setParameter('userId', $userId)
            ->getQuery();
        $result = $qb->getOneOrNullResult();

        return $result;
    }

    public function getPublishedPosts()
    {
        $result = $this->createQueryBuilder('p')
            ->select('p', 'u')
            ->leftJoin('p.user', 'u')
            ->where('p.status = :status')
            ->setParameter('status', 'Published')
            ->getQuery()
            ->getArrayResult();

        return $result;
    }

    public function getPublishedPost($id)
    {
        $qb = $this->createQueryBuilder('p')
            ->select('p', 'u')
            ->leftJoin('p.user', 'u')
            ->where('p.id = :id')
            ->andWhere('p.status = :status')
            ->setParameter('id', $id)
            ->setParameter('status', 'Published')
            ->getQuery();
        $result = $qb->getOneOrNullResult();
        
        return $result;
    }
}
