<?php

namespace AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getAllUsers()
    {
        $result = $this->createQueryBuilder('u')
            ->select('u', 'r')
            ->join('u.roles', 'r')
            ->getQuery()
            ->getArrayResult();

        return $result;
    }
}
